
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "United Summit",
  "details": "Um evento para quem é apaixonado por programação",
  "maximumAttendees": 100
}

###

POST http://localhost:3333/events/da569e5e-be8e-4600-a7d4-17db63cc07b8/attendees
Content-Type: application/json

{
  "name": "Denison",
  "email": "denis2@email.com"
}

###

GET http://localhost:3333/events/da569e5e-be8e-4600-a7d4-17db63cc07b8


###
GET http://localhost:3333/attendees/11/badge